spring:
  security:
    oauth2:
      client:
        registration:
          twitter:
            client-id: ${TWITTER_CLIENT_ID}
            client-secret: ${TWITTER_CLIENT_SECRET}
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/connections/twitter"
            scope:
              - users.read
              - tweet.read
        provider:
          twitter:
            authorization-uri: https://twitter.com/i/oauth2/authorize
            token-uri: https://api.twitter.com/2/oauth2/token


logging:
  level:
    tech.zone2: debug
